[book]
title = "MASH Installer"
authors = ["Bard â€” Drunken Dwarf Runesmith"]
language = "en"
src = "src"

[output.html]
site-url = "/Mash-installer/"
git-repository-url = "https://github.com/drtweak86/Mash-installer"
edit-url-template = "https://github.com/drtweak86/Mash-installer/edit/main/docs/{path}"
